const STORE_ORDER=['民德路店','红谷滩店','抚河桥店','抚州高新店','朝阳店','京东天虹店','赣州店','万年店','九江中航城店','九江万达店','婺源店','杭州西溪天街店','新余店','新余渝水店','台州椒江店','南康店','青岛店','萍乡店','萍乡安源店','温州时代店','台州路桥店','鹰潭月湖店','宜春店','宜春袁州店','杭州市中心店','合肥经开店','泉州兴贤路店'];
const COLORS=['#5a7d9a','#e07b5a','#4ea597','#d4a853','#8b7ec4','#5d9bd5'];
const SUM_FIELDS=new Set(['总营业额','美团核销','抖音核销','抖音访问人数','美团访问人数','新增好评','新增差评','开卡金额','续充金额','抖音扫码','美团扫码','168项目','298项目','358项目','商品销售数量','免单','卡金']);
const AVG_FIELDS=new Set(['美团平均回复时长','30s回复率','5min回复率','美团评分','抖音评分','大众评分','美团经营分','大钟率']);
const MONEY_FIELDS=new Set(['总营业额','美团核销','抖音核销','开卡金额','续充金额','免单','卡金']);
const PCT_FIELDS=new Set(['30s回复率','5min回复率','大钟率']);
const COMPARE_METRICS=['总营业额','美团核销','抖音核销','项目总数','大钟率','新增好评','新增差评','美团经营分'];
let DATA={records:[],dates:[],stores:[],meta:{}};let activeMetric='总营业额';let charts={};let detailPeriodMode='week';let detailPeriodValue='';

const $=id=>document.getElementById(id);const num=v=>Number.isFinite(Number(v))?Number(v):0;
const fmt=(v,field)=>{if(PCT_FIELDS.has(field))return `${(num(v)*100).toFixed(1)}%`;if(field.includes('评分'))return num(v).toFixed(1);if(field==='美团经营分')return num(v).toFixed(1);if(MONEY_FIELDS.has(field))return `¥${Math.round(num(v)).toLocaleString()}`;return Math.round(num(v)).toLocaleString()};
const chart=id=>charts[id]||(charts[id]=echarts.init($(id)));
function getRows(){const start=$('start-date').value,end=$('end-date').value,store=$('store-filter').value;return DATA.records.filter(r=>(!start||r.日期>=start)&&(!end||r.日期<=end)&&(!store||r.门店===store));}
function aggregate(rows,field){if(field==='项目总数')return ['168项目','298项目','358项目'].reduce((s,f)=>s+aggregate(rows,f),0);const values=rows.map(r=>r[field]).filter(v=>v!==null&&v!==''&&Number.isFinite(Number(v))).map(Number);if(!values.length)return 0;return AVG_FIELDS.has(field)?values.reduce((a,b)=>a+b,0)/values.length:values.reduce((a,b)=>a+b,0);}
function group(rows,key){return rows.reduce((m,r)=>((m[r[key]]??=[]).push(r),m),{});}
function storeSort(a,b){const ai=STORE_ORDER.indexOf(a),bi=STORE_ORDER.indexOf(b);return (ai<0?999:ai)-(bi<0?999:bi)||a.localeCompare(b,'zh-CN');}
function setChart(id,option){const c=chart(id);const light=JSON.parse(JSON.stringify(option).replaceAll('#92a0b4','#667085').replaceAll('#c7d0dd','#344054').replaceAll('#273244','#eaecf0').replaceAll('#f2f5f9','#101828').replaceAll('#182230','#ffffff').replaceAll('#39475b','#d0d5dd').replaceAll('#e0ae4f','#6c5ce7').replaceAll('rgba(224,174,79,.10)','rgba(108,92,231,.10)').replaceAll('#3c78b5','#8b7cf6'));c.setOption({backgroundColor:'transparent',color:COLORS,textStyle:{color:'#667085'},tooltip:{trigger:'axis',backgroundColor:'#ffffff',borderColor:'#d0d5dd',extraCssText:'box-shadow:0 8px 24px rgba(16,24,40,.10);',textStyle:{color:'#101828'}},grid:{left:55,right:24,top:34,bottom:42},...light},true);}
function delta(cur,prev,bad=false,label='较前一日'){if(!prev)return '<span class="sub">暂无环比基准</span>';const p=(cur-prev)/Math.abs(prev);const good=bad?p<=0:p>=0;return `<span class="sub delta ${good?'up':'down'}">${p>=0?'↑':'↓'} ${Math.abs(p*100).toFixed(1)}% ${label}</span>`;}
function previousRows(rows){const dates=[...new Set(rows.map(r=>r.日期))].sort();if(!dates.length)return[];const first=dates[0],idx=DATA.dates.indexOf(first);if(idx<=0)return[];const prevDates=DATA.dates.slice(Math.max(0,idx-dates.length),idx);const stores=new Set(rows.map(r=>r.门店));return DATA.records.filter(r=>prevDates.includes(r.日期)&&stores.has(r.门店));}
function renderKpis(container,rows,fields,comparison=null){const prev=comparison?.rows??previousRows(rows),deltaLabel=comparison?.label??'较前一日';$(container).innerHTML=fields.map(([field,label,bad])=>{const val=aggregate(rows,field),pv=aggregate(prev,field);return `<div class="kpi"><div class="label">${label}</div><div class="value">${fmt(val,field)}</div>${delta(val,pv,bad,deltaLabel)}</div>`}).join('');}
function renderOverview(){const rows=getRows(),dates=[...new Set(rows.map(r=>r.日期))].sort();$('overview-title').textContent=dates.length===1?`${dates[0]} 经营日报`:`${dates[0]||'—'} 至 ${dates.at(-1)||'—'}`;$('overview-subtitle').textContent=`${new Set(rows.map(r=>r.门店)).size} 家门店 · ${rows.length} 条日报`;
 renderKpis('kpis',rows,[['总营业额','总营业额'],['项目总数','项目总数'],['美团核销','美团核销'],['抖音核销','抖音核销'],['开卡金额','开卡金额'],['续充金额','续充金额']]);
 const byStore=group(rows,'门店'),ranking=Object.entries(byStore).map(([s,rs])=>[s,aggregate(rs,'总营业额')]).sort((a,b)=>b[1]-a[1]);const top=ranking[0]||['—',0],avg=ranking.length?ranking.reduce((s,x)=>s+x[1],0)/ranking.length:0;const big=aggregate(rows,'大钟率');$('insights').innerHTML=`<div class="insight">营收第一：<strong>${top[0]}</strong>，${fmt(top[1],'总营业额')}</div><div class="insight">单店平均营收：<strong>${fmt(avg,'总营业额')}</strong></div><div class="insight">大钟率：<strong>${fmt(big,'大钟率')}</strong>，高客单项目占比</div>`;
 renderTrend(rows);renderMix(rows);renderRank(ranking);renderAlerts(byStore);}
function renderTrend(rows){const byDate=group(rows,'日期'),dates=Object.keys(byDate).sort();setChart('trend-chart',{legend:{data:['总营业额','项目总数'],textStyle:{color:'#92a0b4'}},xAxis:{type:'category',data:dates,axisLabel:{color:'#92a0b4'}},yAxis:[{type:'value',axisLabel:{color:'#92a0b4',formatter:v=>`¥${v/1000}k`},splitLine:{lineStyle:{color:'#273244'}}},{type:'value',axisLabel:{color:'#92a0b4'},splitLine:{show:false}}],series:[{name:'总营业额',type:'line',smooth:true,symbolSize:6,data:dates.map(d=>aggregate(byDate[d],'总营业额')),lineStyle:{color:COLORS[0],width:3},itemStyle:{color:COLORS[0]},areaStyle:{color:'rgba(224,174,79,.10)'}},{name:'项目总数',type:'bar',yAxisIndex:1,data:dates.map(d=>aggregate(byDate[d],'项目总数')),itemStyle:{color:'rgba(84,166,255,.52)',borderRadius:[3,3,0,0]}}]});}
const DONUT_COLORS=['#5a7d9a','#4ea597','#d4a853','#e07b5a'];function renderMix(rows){const items=[['168项目',aggregate(rows,'168项目')],['298项目',aggregate(rows,'298项目')],['358项目',aggregate(rows,'358项目')],['商品销售',aggregate(rows,'商品销售数量')]];setChart('mix-chart',{tooltip:{trigger:'item'},legend:{bottom:8,textStyle:{color:'#92a0b4'}},series:[{type:'pie',radius:['43%','70%'],center:['50%','45%'],label:{color:'#f2f5f9',formatter:'{b}\n{d}%'},data:items.map(([name,value],i)=>({name,value,itemStyle:{color:DONUT_COLORS[i]}}))}]});}
function renderRank(ranking){const list=ranking.slice(0,15).reverse();setChart('rank-chart',{grid:{left:105,right:55,top:20,bottom:25},xAxis:{type:'value',axisLabel:{color:'#92a0b4',formatter:v=>`${Math.round(v/1000)}k`},splitLine:{lineStyle:{color:'#273244'}}},yAxis:{type:'category',data:list.map(x=>x[0]),axisLabel:{color:'#c7d0dd'}},series:[{type:'bar',data:list.map((x,i)=>({value:x[1],itemStyle:{color:i===list.length-1?COLORS[0]:'#3c78b5',borderRadius:[0,4,4,0]}})),label:{show:true,position:'right',color:'#c7d0dd',formatter:p=>Math.round(p.value).toLocaleString()}}]});chart('rank-chart').off('click');chart('rank-chart').on('click',p=>openStore(p.name));}
function renderAlerts(byStore){const alerts=[];for(const [store,rows] of Object.entries(byStore)){const bad=aggregate(rows,'新增差评'),score=aggregate(rows,'美团评分'),reply=aggregate(rows,'30s回复率'),rev=aggregate(rows,'总营业额');if(bad>0)alerts.push({level:'high',store,text:`新增差评 ${bad} 条`,note:'优先复盘差评内容并闭环'});if(score>0&&score<4.5)alerts.push({level:'high',store,text:`美团评分 ${score.toFixed(1)}`,note:'低于4.5，影响平台转化'});if(reply>0&&reply<.5)alerts.push({level:'mid',store,text:`30秒回复率 ${(reply*100).toFixed(0)}%`,note:'客服响应需要提速'});if(rev===0)alerts.push({level:'mid',store,text:'营业额为 0',note:'检查是否缺报或停业'});}alerts.sort((a,b)=>a.level.localeCompare(b.level));$('alerts').innerHTML=alerts.length?alerts.slice(0,20).map(a=>`<div class="alert"><span class="alert-badge ${a.level}">${a.level==='high'?'紧急':'关注'}</span><div><b>${a.store}</b> · ${a.text}<small>${a.note}</small></div></div>`).join(''):'<div class="alert"><div>当前筛选周期无明显预警</div></div>';}
function renderCompare(){const rows=getRows(),byStore=group(rows,'门店');$('metric-pills').innerHTML=COMPARE_METRICS.map(m=>`<button class="${m===activeMetric?'active':''}" data-metric="${m}">${m}</button>`).join('');$('metric-pills').querySelectorAll('button').forEach(b=>b.onclick=()=>{activeMetric=b.dataset.metric;renderCompare()});const values=Object.entries(byStore).map(([s,rs])=>[s,aggregate(rs,activeMetric)]).sort((a,b)=>b[1]-a[1]);$('compare-chart-title').textContent=`${activeMetric}排行`;const list=values.slice().reverse();setChart('compare-chart',{grid:{left:110,right:65,top:20,bottom:25},xAxis:{type:'value',axisLabel:{color:'#92a0b4'},splitLine:{lineStyle:{color:'#273244'}}},yAxis:{type:'category',data:list.map(x=>x[0]),axisLabel:{color:'#c7d0dd'}},series:[{type:'bar',data:list.map(x=>x[1]),itemStyle:{color:COLORS[0],borderRadius:[0,4,4,0]},label:{show:true,position:'right',color:'#c7d0dd',formatter:p=>fmt(p.value,activeMetric)}}]});const cols=['门店','总营业额','项目总数','大钟率','美团核销','抖音核销','新增好评','新增差评','美团经营分'];$('compare-head').innerHTML='<tr>'+cols.map(x=>`<th>${x}</th>`).join('')+'</tr>';$('compare-body').innerHTML=values.map(([s])=>{const rs=byStore[s];return '<tr>'+cols.map(c=>`<td>${c==='门店'?s:fmt(aggregate(rs,c),c)}</td>`).join('')+'</tr>'}).join('');$('compare-count').textContent=`共 ${values.length} 家门店`;}
function openStore(store){$('store-filter').value=store;detailPeriodValue='';document.querySelector('[data-tab="detail"]').click();renderAll();}
function dateFromText(text){return new Date(`${text}T00:00:00Z`)}
function dateText(date){return date.toISOString().slice(0,10)}
function weekStart(text){const date=dateFromText(text),day=date.getUTCDay()||7;date.setUTCDate(date.getUTCDate()-day+1);return dateText(date)}
function periodKey(text){return detailPeriodMode==='week'?weekStart(text):text.slice(0,7)}
function periodLabel(key){if(detailPeriodMode==='month'){const [year,month]=key.split('-');return `${year}年${Number(month)}月`}const end=dateFromText(key);end.setUTCDate(end.getUTCDate()+6);return `${key} 至 ${dateText(end)}`}
function previousDetailPeriodKey(){if(detailPeriodMode==='week'){const date=dateFromText(detailPeriodValue);date.setUTCDate(date.getUTCDate()-7);return dateText(date)}const date=dateFromText(`${detailPeriodValue}-01`);date.setUTCMonth(date.getUTCMonth()-1);return dateText(date).slice(0,7)}
function syncDetailPeriod(store){const storeRows=DATA.records.filter(r=>r.门店===store),keys=[...new Set(storeRows.map(r=>periodKey(r.日期)))].sort();if(!keys.includes(detailPeriodValue))detailPeriodValue=keys.at(-1)||'';$('detail-period-label').textContent=detailPeriodMode==='week'?'选择周':'选择月';$('detail-period-value').innerHTML=keys.slice().reverse().map(key=>`<option value="${key}" ${key===detailPeriodValue?'selected':''}>${periodLabel(key)}</option>`).join('');document.querySelectorAll('#detail-period-tabs button').forEach(button=>button.classList.toggle('active',button.dataset.mode===detailPeriodMode));return storeRows.filter(r=>periodKey(r.日期)===detailPeriodValue)}
function renderDetail(){let store=$('store-filter').value||DATA.stores.slice().sort(storeSort)[0]||'';const rows=syncDetailPeriod(store),previousKey=previousDetailPeriodKey(),previousPeriodRows=DATA.records.filter(r=>r.门店===store&&periodKey(r.日期)===previousKey),comparison={rows:previousPeriodRows,label:detailPeriodMode==='week'?'较前一周':'较上月'},byDate=group(rows,'日期'),dates=Object.keys(byDate).sort();$('detail-title').textContent=store||'单店详情';$('detail-period-summary').textContent=`${periodLabel(detailPeriodValue)} · ${rows.length}天数据`;renderKpis('detail-kpis',rows,[['总营业额','营业额'],['项目总数','项目总数'],['大钟率','大钟率'],['新增好评','新增好评'],['新增差评','新增差评',true],['美团经营分','美团经营分']],comparison);const axis={type:'category',data:dates,axisLabel:{color:'#92a0b4'}};const y={type:'value',axisLabel:{color:'#92a0b4'},splitLine:{lineStyle:{color:'#273244'}}};setChart('detail-revenue',{legend:{data:['总营业额','美团核销','抖音核销'],textStyle:{color:'#92a0b4'}},xAxis:axis,yAxis:y,series:['总营业额','美团核销','抖音核销'].map((f,i)=>({name:f,type:'line',smooth:true,data:dates.map(d=>aggregate(byDate[d],f)),itemStyle:{color:COLORS[i]},lineStyle:{color:COLORS[i]}}))});setChart('detail-project',{legend:{bottom:5,textStyle:{color:'#92a0b4'}},tooltip:{trigger:'item'},series:[{type:'pie',radius:['42%','70%'],data:['168项目','298项目','358项目'].map((f,i)=>({name:f,value:aggregate(rows,f),itemStyle:{color:DONUT_COLORS[i]}}))}]});setChart('detail-channel',{legend:{data:['抖音访问人数','美团访问人数','抖音核销','美团核销'],textStyle:{color:'#92a0b4'}},xAxis:axis,yAxis:y,series:['抖音访问人数','美团访问人数','抖音核销','美团核销'].map((f,i)=>({name:f,type:i<2?'line':'bar',data:dates.map(d=>aggregate(byDate[d],f)),itemStyle:{color:COLORS[i]},lineStyle:{color:COLORS[i]}}))});setChart('detail-service',{legend:{data:['美团评分','抖音评分','30s回复率'],textStyle:{color:'#92a0b4'}},xAxis:axis,yAxis:[{...y,min:0,max:5},{...y,min:0,max:1,axisLabel:{color:'#92a0b4',formatter:v=>`${v*100}%`}}],series:[['美团评分',0],['抖音评分',0],['30s回复率',1]].map(([f,yi],i)=>({name:f,type:'line',yAxisIndex:yi,smooth:true,data:dates.map(d=>aggregate(byDate[d],f)),itemStyle:{color:COLORS[i]},lineStyle:{color:COLORS[i]}}))});}
function renderAll(){renderOverview();renderCompare();renderDetail();}
function setRange(days){const dates=DATA.dates;if(!dates.length)return;const end=dates.at(-1);$('end-date').value=end;$('start-date').value=days===0?dates[0]:dates[Math.max(0,dates.length-days)];document.querySelectorAll('#quick-range button').forEach(b=>b.classList.toggle('active',Number(b.dataset.days)===days));renderAll();}
function exportCsv(){const rows=getRows(),fields=DATA.fields;const cell=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv='\ufeff'+[fields.join(','),...rows.map(r=>fields.map(f=>cell(r[f])).join(','))].join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`民德日报_${$('start-date').value}_${$('end-date').value}.csv`;a.click();URL.revokeObjectURL(a.href);showToast(`已导出 ${rows.length} 条明细`);}
function showToast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800);}
async function init(){try{if(window.DASHBOARD_DATA){DATA=window.DASHBOARD_DATA}else{const res=await fetch('data/dashboard_data.json',{cache:'no-store'});if(!res.ok)throw new Error(`HTTP ${res.status}`);DATA=await res.json()}DATA.dates.sort();DATA.stores.sort(storeSort);$('store-filter').innerHTML='<option value="">全部门店</option>'+DATA.stores.map(s=>`<option>${s}</option>`).join('');$('freshness').textContent=`更新 ${new Date(DATA.meta.generated_at).toLocaleString('zh-CN',{hour12:false})} · 最新 ${DATA.meta.date_max}`;setRange(1);
 document.querySelectorAll('#tabs .tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');setTimeout(()=>Object.values(charts).forEach(c=>c.resize()),0)});document.querySelectorAll('#quick-range button').forEach(b=>b.onclick=()=>setRange(Number(b.dataset.days)));['start-date','end-date'].forEach(id=>$(id).onchange=()=>{document.querySelectorAll('#quick-range button').forEach(b=>b.classList.remove('active'));renderAll()});$('store-filter').onchange=()=>{detailPeriodValue='';renderAll()};document.querySelectorAll('#detail-period-tabs button').forEach(button=>button.onclick=()=>{detailPeriodMode=button.dataset.mode;detailPeriodValue='';renderDetail()});$('detail-period-value').onchange=()=>{detailPeriodValue=$('detail-period-value').value;renderDetail()};$('export-btn').onclick=exportCsv;window.addEventListener('resize',()=>Object.values(charts).forEach(c=>c.resize()));}catch(e){$('freshness').textContent='数据加载失败';document.querySelector('main').innerHTML=`<article class="card" style="padding:30px">无法加载日报数据：${e.message}<br><small>请先运行 node scripts/pull_base_data.js，并通过本地服务器打开页面。</small></article>`;}}
init();
